rest_admin_username: admin
rest_admin_password: letmein
rest_port: 31200
kube_config_path: ~/.kube/config
log_level: debug
db_username: root
db_password: root
db_name: ksv
db_address: "10.106.213.189:3306"
